"use client";

import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/store";
import { AuthProvider } from "@/auth/JwtContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="robots" content="index, follow" />
        <title>Mundo Tango</title>
        <meta name="description" content="Generated by trangotech" />
      </head>
      <body>
        <Provider store={store}>
          <AuthProvider>
            <Toaster />
            {children}
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}