import { Toaster } from "react-hot-toast";
import "./globals.css";
import AdSense from "@/components/Adsense/Adsense";

export const metadata = {
  title: "Mundo Tango",
  description: "Generated by trangotech",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="robots" content="index, follow" />
        {/* <meta
          name="google-adsense-account"
          content={
            process.env.NODE_ENV === "production"
              ? process.env.PUBLIISH_ID_GOOGLE
              // : "ca-pub-0000000000000000"
              : 'ca-pub-7838078349094645'
          }
        />
        <AdSense
          pId={
            process.env.NODE_ENV === "production"
              ? process.env.PUBLIISH_ID_GOOGLE
              // : "ca-pub-0000000000000000"
              : 'ca-pub-7838078349094645'
          }
        /> */}
        {/* <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' https://googleads.g.doubleclick.net https://pagead2.googlesyndication.com https://tpc.googlesyndication.com; frame-src 'self' https://googleads.g.doubleclick.net; img-src 'self' https://googleadservices.com; style-src 'self'; font-src 'self';"/> */}
      </head>
      <body>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
