

module.exports = {
    testRouter: require('./test'),
    userRoutes: require("./User"),
    adminRoutes: require("./Admin"),
    controllerRoutes: require("./RoutesController"),
    postRoutes: require("./Post"),
    postShareRoutes: require("./PostShare"),
    activityRoutes: require("./Activity"),
    feelingRoutes: require("./Feeling"),
    nonTangoActivityRoutes: require("./NonTangoActivities"),
    postLikeRoutes: require("./PostLike"),
    friendRoutes: require("./Friend"),
    reportTypeRoutes: require("./ReportType"),
    eventTypeRoutes: require("./EventTypes"),
    postCommentRoutes: require("./PostComment"),
    groupRoutes: require("./Group"),
    pageRoutes: require("./Page"),
    groupActivityRoutes: require("./GroupActivity"),
    eventRoutes: require("./Event"),
    postCommentLikeRoutes: require("./PostCommentLike"),
    notificationRoutes: require("./Notifications"),
    subscriptionRoutes: require("./Subscription"),
    userTravellingRoutes: require("./UserTravelling"),
    reportRoutes: require("./Report"),
    blockedUserRoutes: require("./BlockedUser"),
    languageRoutes: require("./Language"),
}